---
- name: Clean up old monitoring stack
  shell: docker-compose down
  args:
    chdir: "{{ playbook_dir }}/.."
  ignore_errors: true

- name: Force remove specific containers just in case
  shell: docker rm -f grafana prometheus ryu_exporter sflow-rt || true

- name: Ensure monitoring stack is started
  shell: docker-compose up -d --build
  args:
    chdir: "{{ playbook_dir }}/.."
  register: monitoring_result
  failed_when: monitoring_result.rc != 0

- name: Show monitoring deployment result
  debug:
    msg: "{{ monitoring_result.stdout_lines }}"

- name: Wait for Prometheus to be ready
  uri:
    url: http://127.0.0.1:9090/-/healthy
    method: GET
    status_code: 200
  register: prometheus_health
  retries: 10
  delay: 3
  until: prometheus_health.status == 200

- name: Wait for Grafana to be ready
  uri:
    url: http://127.0.0.1:3001/login
    method: GET
    status_code: 200
  register: grafana_health
  retries: 10
  delay: 3
  until: grafana_health.status == 200

- name: Wait for sFlow-RT to be ready
  uri:
    url: http://127.0.0.1:8008
    method: GET
    status_code: 200
  register: sflowrt_health
  retries: 10

- name: Check sFlow configuration
  shell: ovs-vsctl list sflow
  become: yes
  register: sflow_check
  changed_when: false

- name: Show sFlow configuration
  debug:
    msg: "{{ sflow_check.stdout_lines }}"