version: "3.8"

services:
  ryu_exporter:
    build:
      context: .
      dockerfile: docker/Dockerfile.exporter
    container_name: ryu_exporter
    environment:
      - RYU_STATS_URL=http://sdn-controller:8080/stats/port/ALL
    ports:
      - "8000:8000"
    networks:
      - sdn_net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # Sauvegarde l'historique des métriques
      - prometheus_data:/prometheus 
    ports:
      - "9090:9090"
    networks:
      - sdn_net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      # Sauvegarde tes Dashboards et Data Sources
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - sdn_net
    restart: unless-stopped

  # 👇 NOUVEAU SERVICE SFLOW-RT AJOUTÉ ICI
  sflow-rt:
    image: sflow/prometheus
    container_name: sflow-rt
    ports:
      - "6343:6343/udp"  # Port UDP où les switchs OVS envoient les paquets sFlow
      - "8008:8008"      # Port TCP pour l'API sFlow-RT et Prometheus
    networks:
      - sdn_net
    restart: unless-stopped

networks:
  sdn_net:
    external: true

# Déclaration des disques durs virtuels
volumes:
  grafana_data:
  prometheus_data: