name: SDN CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: self-hosted
    env:
      PYTHONDONTWRITEBYTECODE: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Build Docker image
        run: docker build -t mon-ryu:v2 -f docker/Dockerfile .

      - name: Run CI playbook
        run: ansible-playbook ansible/deploy_ci.yml -i ansible/inventory.ini